#server:
#  port: 8082
#  context-path: /app
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/ts
#    username: postgres
#    password: sql
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL94Dialect
#    database: postgresql
#  liquibase:
#    change-log: db/changelog/db.changelog-master.xml
#    enabled: true
#  sql:
#    init:
#      mode: embedded
#      data-locations: database/filingDB.sql

